/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pack1;

/**
 *
 * @author sai
 */
public class startUp extends javax.swing.JFrame {

    /**
     * Creates new form startUp
     */
    public startUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        p1 = new javax.swing.JPanel();
        OFactory = new javax.swing.JLabel();
        Cobject = new javax.swing.JButton();
        ADTobject = new javax.swing.JButton();
        SMobject = new javax.swing.JButton();
        Relationship = new javax.swing.JLabel();
        ERObject = new javax.swing.JButton();
        Classhierarchy = new javax.swing.JButton();
        Transform = new javax.swing.JLabel();
        DFDobject = new javax.swing.JButton();
        CFDobject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OOAD CASE TOOL");

        p1.setBackground(new java.awt.Color(102, 102, 102));

        OFactory.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        OFactory.setText("Object Factory");

        Cobject.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Cobject.setText("C Object");
        Cobject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobjectActionPerformed(evt);
            }
        });

        ADTobject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ADTobject.setText("ADT Object");
        ADTobject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADTobjectActionPerformed(evt);
            }
        });

        SMobject.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SMobject.setText("SM Object");
        SMobject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMobjectActionPerformed(evt);
            }
        });

        Relationship.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Relationship.setText("Relationship Tool");

        ERObject.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ERObject.setText("ER");
        ERObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERObjectActionPerformed(evt);
            }
        });

        Classhierarchy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Classhierarchy.setText("Class Hierarchy");
        Classhierarchy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasshierarchyActionPerformed(evt);
            }
        });

        Transform.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Transform.setText("Transformations");

        DFDobject.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DFDobject.setText("DFD");
        DFDobject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFDobjectActionPerformed(evt);
            }
        });

        CFDobject.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CFDobject.setText("CFD");
        CFDobject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFDobjectActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sai\\Desktop\\logo_511678_web.jpg")); // NOI18N

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("     Harish Kanagaraj\n    Karthik Karuppaiah\n      Akshayalakshmi\n          Deepthi BV\n        Swetha Reddy\n           Saiprem\n        Vikram Reddy\n         Sai Rakesh");
        jTextArea3.setBorder(null);
        jTextArea3.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(Classhierarchy, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(ERObject, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(OFactory))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Relationship)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addComponent(Cobject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(SMobject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(ADTobject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(CFDobject, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(Transform))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(DFDobject, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(OFactory)
                .addGap(40, 40, 40)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cobject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SMobject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADTobject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Relationship)
                .addGap(38, 38, 38)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ERObject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Classhierarchy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Transform, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DFDobject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CFDobject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(308, 308, 308))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });
        File.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                FileAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        File.add(exit);

        Menu.add(File);

        Help.setText("help");
        Menu.add(Help);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_FileAncestorMoved

    }//GEN-LAST:event_FileAncestorMoved

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed

    }//GEN-LAST:event_FileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void CFDobjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFDobjectActionPerformed
        CFD cfd = new CFD();
        cfd.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_CFDobjectActionPerformed

    private void DFDobjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFDobjectActionPerformed
        DFD dfd = new DFD();
        dfd.setVisible(true);
        
    }//GEN-LAST:event_DFDobjectActionPerformed

    private void ClasshierarchyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasshierarchyActionPerformed
        CH ch = new CH();
        ch.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_ClasshierarchyActionPerformed

    private void ERObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERObjectActionPerformed
        ER er = new ER();
        er.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_ERObjectActionPerformed

    private void SMobjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMobjectActionPerformed
        SMObject sm = new SMObject();
        sm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SMobjectActionPerformed

    private void ADTobjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADTobjectActionPerformed
        ADTObject adt = new ADTObject();
        adt.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ADTobjectActionPerformed

    private void CobjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobjectActionPerformed
        CObject c = new CObject();
        c.setVisible(true);
        //new startUp().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_CobjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADTobject;
    private javax.swing.JButton CFDobject;
    private javax.swing.JButton Classhierarchy;
    private javax.swing.JButton Cobject;
    private javax.swing.JButton DFDobject;
    private javax.swing.JButton ERObject;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel OFactory;
    private javax.swing.JLabel Relationship;
    private javax.swing.JButton SMobject;
    private javax.swing.JLabel Transform;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel p1;
    // End of variables declaration//GEN-END:variables
}
